<?php

defined( 'ABSPATH' ) || exit;

/**
 * Limit stored Elementor background CSS to rules generated by this plugin.
 */
final class Travelfic_Toolkit_Background_CSS {
	public static function legacy_element_rule( $element_id, $image_url ) {
		if ( ! is_string( $element_id ) || ! preg_match( '/^[a-zA-Z0-9_-]{1,64}$/D', $element_id ) ) {
			return '';
		}

		$url = self::safe_url( $image_url );
		return '' === $url ? '' : '.elementor-element-' . $element_id . ' { background-image: url("' . $url . '"); } ';
	}

	public static function rule( $element_id, $image_url, $icon = false ) {
		if ( ! is_string( $element_id ) || ! preg_match( '/^[a-zA-Z0-9_-]{1,64}$/D', $element_id ) ) {
			return '';
		}

		$url = self::safe_url( $image_url );
		if ( '' === $url ) {
			return '';
		}

		$selector = '[data-id="' . $element_id . '"]';
		if ( $icon ) {
			return $selector . ' .elementor-icon { background-image: url("' . $url . '"); background-repeat: no-repeat; background-position: center center; } ';
		}

		return $selector . ' { background-image: url("' . $url . '"); } ';
	}

	public static function sanitize_rules( $css ) {
		if ( ! is_string( $css ) || strlen( $css ) > 262144 ) {
			return '';
		}

		$rules = array();
		foreach ( explode( '}', $css ) as $fragment ) {
			$fragment = trim( $fragment );
			if ( '' === $fragment ) {
				continue;
			}
			if ( ! preg_match( '/^\[data-id="([a-zA-Z0-9_-]{1,64})"\](\s+\.elementor-icon)?\s*\{\s*background-image:\s*url\("([^"\r\n]*)"\);(?:\s*background-repeat:\s*no-repeat;\s*background-position:\s*center center;)?\s*$/D', $fragment, $matches ) ) {
			continue;
			}
			$rule = self::rule( $matches[1], $matches[3], ! empty( $matches[2] ) );
			if ( '' !== $rule ) {
				$rules[] = $rule;
			}
		}

		return implode( "\n", $rules );
	}

	private static function safe_url( $url ) {
		if ( ! is_string( $url ) || strlen( $url ) > 2048 || preg_match( '/[\x00-\x20"\x27()\\\\<>]/', $url ) ) {
			return '';
		}

		$parts = wp_parse_url( $url );
		if ( ! is_array( $parts ) || ! isset( $parts['scheme'], $parts['host'] ) ||
			! in_array( strtolower( $parts['scheme'] ), array( 'http', 'https' ), true ) ) {
			return '';
		}

		return esc_url_raw( $url );
	}
}
